Thing 2 ready for review
au-research/ARDC-23-things pull request #16
Opened 2019-12-18 00:46 UTC by ragamouf

2019-12-18 05:15 UTC, NicholaBurton commented on source/www.ands.org.au/working-with-data/skills/23-research-data-things/all23/thing-2.md
> +**[Jump to Thing 3&gt;&gt;](thing-3.md)**
**[&lt;&lt;Jump to Thing 1](thing-1.md) &nbsp; &nbsp; [Jump to Thing 3&gt;&gt;](thing-3.md)**

2019-12-18 05:17 UTC, NicholaBurton commented on source/www.ands.org.au/working-with-data/skills/23-research-data-things/all23/thing-2.md
> +### Digital data in Lab Notebooks**
Some extra ** have snuck in :)

2019-12-18 05:25 UTC, NicholaBurton requested changes
Looking good, just caught a couple of things!

2019-12-18 05:25 UTC, NicholaBurton commented on source/www.ands.org.au/working-with-data/skills/23-research-data-things/all23/thing-2.md
> +Tweet to [@ardc_au](https://twitter.com/ardc_au) using \#23things
lines 108 and 109 should be bulleted

2019-12-18 05:25 UTC, NicholaBurton commented on source/www.ands.org.au/working-with-data/skills/23-research-data-things/all23/thing-2.md
> +### Digital data in Lab Notebooks**
Some extra ** have snuck in :)

2019-12-18 05:25 UTC, NicholaBurton commented on source/www.ands.org.au/working-with-data/skills/23-research-data-things/all23/thing-2.md
> +**[Jump to Thing 3&gt;&gt;](thing-3.md)**
**[&lt;&lt;Jump to Thing 1](thing-1.md) &nbsp; &nbsp; [Jump to Thing 3&gt;&gt;](thing-3.md)**

2019-12-18 05:25 UTC, NicholaBurton commented on source/www.ands.org.au/working-with-data/skills/23-research-data-things/all23/thing-2.md
> +Tweet to [@ardc_au](https://twitter.com/ardc_au) using \#23things
lines 144 and 145 should be bulleted

2019-12-18 05:25 UTC, NicholaBurton commented on source/www.ands.org.au/working-with-data/skills/23-research-data-things/all23/thing-2.md
> +Tweet to [@ardc_au](https://twitter.com/ardc_au) using \#23things
lines 77 and 78 should be bulleted

2020-01-10 00:29 UTC, tom-h approved these changes

2020-01-10 00:29 UTC, merged